"use client"

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jCPbMVgFftV
 */
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { useState } from "react";

export function SentimentAnalyze() {

  const [text, setText] = useState("");
  const [sentiment, setSentiment] = useState("");
  const [sentimentScores, setSentimentScores] = useState({} as any);

  const analyzeSentiment = async () => {
    //make a post request to localhost:5000/ana-sentiment
    const res = await fetch("http://localhost:5000/ana-sentiment", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(
        {text: text}
      )
    })

    const data = await res.json();
    setSentiment(data.sentiment);
    setSentimentScores(data.sentiment_score);
  }
  
  return (
    <div className="w-full h-screen flex flex-col items-center justify-center bg-red-100">
      <div className="w-full max-w-md p-8 bg-white rounded-lg shadow-md border-black border">
        <h1 className="text-2xl font-bold text-center mb-4">Sentiment Analyzer</h1>
        <div className="space-y-4"  >
          <Textarea className="min-h-[100px] bg-white" placeholder="Type your text here..." value={text} onChange={(e) => setText(e.target.value)}/>
          <Button className="w-full border-white" onClick={() => analyzeSentiment()}>Analyze Sentiment</Button>
          {sentiment && (
            <>
              <div className={`flex items-center justify-center space-x-2 w-full border-2 border-gray-800 bg-opacity-50 rounded-lg p-2 ${sentiment == "Neutral" ? "bg-gray-500" : sentiment == "Positive" ? "bg-green-500" : "bg-red-500"}`}>
                <p className="text-black flex-grow text-center">
                  {sentiment}
                </p>
              </div>
              <pre className="text-black">
                {sentimentScores && JSON.stringify(sentimentScores, null, 2)}
              </pre>
            </>
          )}
        </div>
      </div>
    </div>
  )
}
